feat: alpha
jaoafa/Javajaotan2 pull request #10
Opened 2021-05-26 12:18 UTC by yuuahp

## 実装・修正した内容の簡単な解説
アルファになったオレを出来るようにしました。
引数配列の中に`random`が含まれていたらシャッフルします。
(言葉の指定と併用可能)

## 関連する Issue

## チェックリスト

> `[ ]` を `[x]` にすることでチェックできます

- [x] 【必須】[CONTRIBUTING](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を読みました
- [x] 【必須】テストサーバで動作確認をしました
  - [x] ローカルサーバで動作確認しました
  - [ ] ZakuroHatのテストサーバで動作確認しました
- [x] 【必須】プロジェクトのコードスタイルに適合しています（IDEAのコミット前処理でフォーマットして下さい）
- [x] 【必須】`NULL` が返却されるかもしれない(`@Nullable`)メソッドや変数は NULL チェックを実装しました
- [x] 非推奨とされているメソッド・クラスなどを使用していません（なるべく推奨されるメソッドなどに置き換える）
  - [ ] 代替メソッド・クラスなどがないため、非推奨メソッドなどを使用しています
- [ ] 複数のクラスにわたって使用される変数があるので、 `MyMaidData` にその変数を作成し管理しています
- [ ] 複数のクラスにわたって多く使用される関数があるので、 `MyMaidLibrary` にその関数を作成し管理しています

## 追加情報

> 何か追加情報がある場合は記載してください

2021-05-26 16:16 UTC, book000 commented
不具合発見: `/alpha a b c d e f g h i j` を実行すると、次のエラーが発生するように見えます（多すぎる引数の場合の処理に不具合あり？）

```
java.lang.ArrayIndexOutOfBoundsException: 6
at com.jaoafa.javajaotan2.command.Cmd_Alpha.getMargedArray(Cmd_Alpha.java:84)
at com.jaoafa.javajaotan2.command.Cmd_Alpha.oreAlpha(Cmd_Alpha.java:66)
```

2021-05-26 17:42 UTC, book000 requested changes

2021-05-26 17:42 UTC, book000 commented on src/main/java/com/jaoafa/javajaotan2/command/Cmd_Alpha.java
> +        );
説明抜けで非常に申し訳ないんですが、

```suggestion
        return new JavajaotanCommand.Detail(
            "alpha",
            "アルファになったオレをします。"
        );
```
で動作します。

ちなみに多分permsは空リストだと誰も実行できなくなっちゃう恐れ。

参考: 
https://github.com/jaoafa/Javajaotan2/blob/52f8d8bcf3e0cbe5b86f9b5ffa5cec6d0242a1cd/src/main/java/com/jaoafa/javajaotan2/lib/JavajaotanCommand.java#L37-L63

2021-05-26 17:44 UTC, book000 commented
権限利用者制限とベータテストの設計に関してはかなり微妙な点があるので、なんか気づいたら言ってください

2021-05-26 23:05 UTC, yuuahp commented
帰ったら修正します👀

2021-05-27 11:20 UTC, yuuahp commented
修正しました✅

2021-05-27 13:52 UTC, book000 approved these changes

2021-05-27 13:52 UTC, merged